### ISSUE TITLE
menage exceptions 

### ISSUE THREAD

**Issue by mgirardi23** [leobouard/PingCastleDashboard#1]
enhancement: I add an `exceptions.csv` file to deal exceptions in the same way of `hcrules.csv`
Exceptions set points = 0 and add comment at the end of the "rationale"
Global Score not updated
hope it could help

### File format

```csv
"Domain";"RiskId";"Rationale"
```

### Code added

```powershell
$exceptions = Import-Csv -Path "$PSScriptRoot\data\exceptions.csv" -Delimiter ';' -Encoding utf8
```

### Code modified

```powershell
$reports = $xmlFiles | ForEach-Object {
	$domain_ok = $false;
	if($exceptions.domain -contains (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/DomainFQDN').Node.'#text'){$domain_ok = $true;$cur_domain = (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/DomainFQDN').Node.'#text'}
    [PSCustomObject]@{
        Domain     = (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/DomainFQDN').Node.'#text'
        Date       = Get-Date (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/GenerationDate').Node.'#text'
        Version    = (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/EngineVersion').Node.'#text'
        Maturity   = (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/MaturityLevel').Node.'#text'
        DomainMode = $functionalLevels[(Select-Xml -Path $_.FullName -XPath '/HealthcheckData/DomainFunctionalLevel').Node.'#text']
        ForestMode = $functionalLevels[(Select-Xml -Path $_.FullName -XPath '/HealthcheckData/ForestFunctionalLevel').Node.'#text']
        Scores     = [PSCustomObject]@{
            Global           = [int](Select-Xml -Path $_.FullName -XPath '/HealthcheckData/GlobalScore').Node.'#text'
            StaleObjects     = [int](Select-Xml -Path $_.FullName -XPath '/HealthcheckData/StaleObjectsScore').Node.'#text'
            PrivilegiedGroup = [int](Select-Xml -Path $_.FullName -XPath '/HealthcheckData/PrivilegiedGroupScore').Node.'#text'
            Trust            = [int](Select-Xml -Path $_.FullName -XPath '/HealthcheckData/TrustScore').Node.'#text'
            Anomaly          = [int](Select-Xml -Path $_.FullName -XPath '/HealthcheckData/AnomalyScore').Node.'#text'
        }
        RiskRules  = (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/RiskRules/HealthcheckRiskRule').Node | ForEach-Object {
	    $points = [int]($_.Points);$rationale = $_.Rationale
            if($domain_ok){
				if($exceptions.riskid -contains $_.riskid){
					$cur_riskid = $_.riskid; $points = 0; 
					$rationale = $_.Rationale + ($exceptions|?{$_.domain -like $cur_domain}|?{$_.riskid -like $cur_riskid}|%{" >---  " + $_.rationale + " ---<"})
				}			}
			$riskId = $_.RiskId
            [PSCustomObject]@{
                Points    = $points
                Level     = ($hcRules | Where-Object { $_.RiskId -eq $riskId }).Level
                Category  = $_.Category
                Model     = $_.Model
                RiskId    = $riskId
                Rationale = $rationale
            }
        }
    }
}
```

**Comment by leobouard** [comment]
Hi mgirardi23,

Thank you for the idea!
An exception list has been added to exclude some risk rules from the dashboard

Léo

**Comment by mgirardi23** [comment]
Many thanks
I also made a little modify on same exception module to add a Note field (reason to justify) and change "ignored" to "Aknowlegde" (my boss hate ignore when it comes to security):


$reports = $xmlFiles | ForEach-Object {
    [PSCustomObject]@{
        Domain     = (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/DomainFQDN').Node.'#text'
        Date       = Get-Date (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/GenerationDate').Node.'#text'
        Version    = (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/EngineVersion').Node.'#text'
        Maturity   = (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/MaturityLevel').Node.'#text'
        DomainMode = $functionalLevels[(Select-Xml -Path $_.FullName -XPath '/HealthcheckData/DomainFunctionalLevel').Node.'#text']
        ForestMode = $functionalLevels[(Select-Xml -Path $_.FullName -XPath '/HealthcheckData/ForestFunctionalLevel').Node.'#text']
        Scores     = [PSCustomObject]@{
            Global           = [int](Select-Xml -Path $_.FullName -XPath '/HealthcheckData/GlobalScore').Node.'#text'
            StaleObjects     = [int](Select-Xml -Path $_.FullName -XPath '/HealthcheckData/StaleObjectsScore').Node.'#text'
            PrivilegiedGroup = [int](Select-Xml -Path $_.FullName -XPath '/HealthcheckData/PrivilegiedGroupScore').Node.'#text'
            Trust            = [int](Select-Xml -Path $_.FullName -XPath '/HealthcheckData/TrustScore').Node.'#text'
            Anomaly          = [int](Select-Xml -Path $_.FullName -XPath '/HealthcheckData/AnomalyScore').Node.'#text'
        }
        RiskRules  = (Select-Xml -Path $_.FullName -XPath '/HealthcheckData/RiskRules/HealthcheckRiskRule').Node | ForEach-Object {
            $riskId = $_.RiskId
            [PSCustomObject]@{
                Points    = [int]($_.Points)
                Level     = ($hcRules | Where-Object { $_.RiskId -eq $riskId }).Level
                Category  = $_.Category
                Model     = $_.Model
                RiskId    = $riskId
                Rationale = $_.Rationale
		Note 	  = $null
            }
        }
        IgnoredRiskRules = $null
    }
}
# Handle exceptions
$exceptions = Import-Csv -Path "$PSScriptRoot\data\exceptions.csv" -Delimiter ";" -Encoding UTF8
$reports | ForEach-Object {
    $domain = $_.Domain
    $domainExceptions = $exceptions | Where-Object { $_.Domain -eq $domain -or $_.Domain -eq '*' }
	$_.IgnoredRiskRules = $_.RiskRules | Where-Object { $_.RiskId -in $domainExceptions.RiskId }
	$_.RiskRules = $_.RiskRules | Where-Object { $_.RiskId -notin $domainExceptions.RiskId }
	$_.IgnoredRiskRules | ForEach-Object {
		$riskId = $_.RiskId
		$exception = $domainExceptions | Where-Object { $_.RiskId -eq $RiskId }
        if ($exception) {
            $_.Note = $exception.Rationale
        }
	}
}

And for the exception table name only
New-HTMLSection -HeaderText **'Acknowledged risk rules'** -Direction column
